// Copyright (C) 2019-2023 Algorand, Inc.
// This file is part of go-algorand
//
// go-algorand is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// go-algorand is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with go-algorand.  If not, see <https://www.gnu.org/licenses/>.

package sortition

import (
	"encoding/hex"
	"encoding/json"
	"math/big"
	"os"
	"testing"
)

type arbDyadicCertificate struct {
	Mantissa string `json:"mantissa"`
	Exponent int64  `json:"exponent"`
}

type arbCDFVector struct {
	Label            string               `json:"label"`
	Money            uint64               `json:"money"`
	TotalMoney       uint64               `json:"total_money"`
	ExpectedSize     uint64               `json:"expected_size"`
	Digest           string               `json:"digest"`
	Want             uint64               `json:"want"`
	PrecisionBits    uint64               `json:"precision_bits"`
	CDFPreviousUpper arbDyadicCertificate `json:"cdf_previous_upper"`
	CDFSelectedLower arbDyadicCertificate `json:"cdf_selected_lower"`
}

type arbCertificateFile struct {
	Format    uint64         `json:"format"`
	Generator string         `json:"generator"`
	Semantics string         `json:"semantics"`
	Vectors   []arbCDFVector `json:"vectors"`
}

func parseCertificateMantissa(t *testing.T, d arbDyadicCertificate) *big.Int {
	t.Helper()
	m, ok := new(big.Int).SetString(d.Mantissa, 10)
	if !ok {
		t.Fatalf("invalid certificate mantissa %q", d.Mantissa)
	}
	return m
}

// compareDyadicToRat compares mantissa*2^exponent with num/den using exact
// integer arithmetic. The certificate endpoints themselves come from Arb;
// this check makes the inequalities carried by the JSON independently
// inspectable by the Go test.
func compareDyadicToRat(t *testing.T, d arbDyadicCertificate, num, den *big.Int) int {
	t.Helper()
	m := parseCertificateMantissa(t, d)
	left, right := new(big.Int).Set(m), new(big.Int).Set(num)
	if d.Exponent >= 0 {
		left.Lsh(left, uint(d.Exponent))
		left.Mul(left, den)
	} else {
		left.Mul(left, den)
		right.Lsh(right, uint(-d.Exponent))
	}
	return left.Cmp(right)
}

// TestSelectF128ArbCertificates consumes offline certificates generated by
// python-flint/Arb's regularized incomplete beta implementation. Unlike all
// in-process floating references, Arb neither initializes at q^money nor uses
// SelectF128's forward PMF recurrence. Every vector first proves the exact
// binomial quantile inequality, then pins SelectF128 to that certified count.
func TestSelectF128ArbCertificates(t *testing.T) {
	raw, err := os.ReadFile("testdata/f128_arb_certificates.json")
	if err != nil {
		t.Fatal(err)
	}
	var certificates arbCertificateFile
	if err := json.Unmarshal(raw, &certificates); err != nil {
		t.Fatal(err)
	}
	if certificates.Format != 1 || certificates.Generator == "" || certificates.Semantics == "" || len(certificates.Vectors) < 10 {
		t.Fatalf("unexpected Arb certificate corpus: format=%d generator=%q semantics=%q vectors=%d",
			certificates.Format, certificates.Generator, certificates.Semantics, len(certificates.Vectors))
	}

	digestDen := new(big.Int).Sub(new(big.Int).Lsh(big.NewInt(1), 256), big.NewInt(1))
	labels := make(map[string]struct{}, len(certificates.Vectors))
	for _, vector := range certificates.Vectors {
		t.Run(vector.Label, func(t *testing.T) {
			if _, exists := labels[vector.Label]; exists || vector.Label == "" {
				t.Fatalf("empty or duplicate certificate label %q", vector.Label)
			}
			labels[vector.Label] = struct{}{}
			if vector.Money >= SelectF128MaxMoney || vector.TotalMoney == 0 || vector.ExpectedSize == 0 ||
				vector.ExpectedSize >= vector.TotalMoney || vector.Want > vector.Money || vector.PrecisionBits < 128 {
				t.Fatalf("invalid certified parameters or result: money=%d total=%d expected=%d want=%d precision=%d",
					vector.Money, vector.TotalMoney, vector.ExpectedSize, vector.Want, vector.PrecisionBits)
			}
			digestBytes, err := hex.DecodeString(vector.Digest)
			if err != nil || len(digestBytes) != DigestSize {
				t.Fatalf("invalid digest %q", vector.Digest)
			}
			var d Digest
			copy(d[:], digestBytes)
			digestInt := new(big.Int).SetBytes(d[:])
			if digestInt.Sign() <= 0 {
				t.Fatal("certificate corpus deliberately excludes the ratio==0 degenerate boundary")
			}
			zero, one := new(big.Int), big.NewInt(1)
			for name, endpoint := range map[string]arbDyadicCertificate{
				"CDF(want-1) upper": vector.CDFPreviousUpper,
				"CDF(want) lower":   vector.CDFSelectedLower,
			} {
				if compareDyadicToRat(t, endpoint, zero, one) < 0 ||
					compareDyadicToRat(t, endpoint, one, one) > 0 {
					t.Fatalf("%s endpoint is outside [0,1]", name)
				}
			}

			// Arb supplied an upper enclosure for CDF(want-1) and a lower
			// enclosure for CDF(want). Exact integer comparison with the
			// digest ratio proves the selected quantile.
			if compareDyadicToRat(t, vector.CDFPreviousUpper, digestInt, digestDen) >= 0 {
				t.Fatal("certificate does not prove CDF(want-1) < ratio")
			}
			if compareDyadicToRat(t, vector.CDFSelectedLower, digestInt, digestDen) < 0 {
				t.Fatal("certificate does not prove ratio <= CDF(want)")
			}
			if inFrozenSliver(vector.Money, digestRatioBig(d, 512)) {
				t.Fatal("exact-math certificate unexpectedly lies in the separately defined frozen sliver")
			}
			if got := SelectF128(vector.Money, vector.TotalMoney, vector.ExpectedSize, d); got != vector.Want {
				t.Fatalf("SelectF128=%d, Arb-certified exact binomial quantile=%d", got, vector.Want)
			}
		})
	}
}
